#!/usr/bin/env bash

set -euo pipefail

site="site"
template="template"

compile() {
    local in="$1"
    local base="$(basename "$1")"
    local out="site/${base%.md}.html"

    pandoc "$in" --standalone --template "${template}/layout.html" -o "$out"
    echo "$out"
}

extract() {
    local in="$1"
    local base="$(basename "$1")"
    local out="site/${base%.md}.clj"
    
    pandoc --filter ./extract-codeblocks.py --to markdown "$in" | grep -vE '^```' > "$out"
    echo "$out"
}

common() {
    cp "${template}/style.css" "${site}"
}

common

fs=(posts/*.md)

for f in ${fs[@]}; do
    compile "$f"
    extract "$f"
done
