#!/usr/bin/env python

import pystache

posts = open("target/posts.html").read().decode("utf-8")
layout = open("template/layout.html").read().decode("utf-8")
bindings = {
    "content": posts
}

out = open("site/index.html", "w")
out.write(pystache.render(layout, bindings).encode("utf-8"))
