#!/usr/bin/env bash

dirs=(posts template build)

./build

inotifywait --exclude out -r -m -e modify ${dirs[@]} |
while read filename eventlist eventfile
do
    echo
    printf "[%s]: Rebuilding ...\n" "$(date)"
    ./build
    echo done
done
