#!/usr/bin/env bash

directory="."

./build

inotifywait --exclude out -r -m -e modify "$directory" |
while read filename eventlist eventfile
do
    echo
    printf "[%s]: Rebuilding ...\n" "$(date)"
    ./build
    echo done
done
