#!/usr/bin/env python

import os

def touch(fname):
    if os.path.exists(fname):
        os.utime(fname, None)
    else:
        open(fname, 'a').close()

def main():
    base = "posts"
    fn = "blubb"
    path = os.path.join(base, fn)
    touch(path)

main()
